import { chromium } from 'playwright-core'
const SHOT = 'C:/Users/gotsb/AppData/Local/Temp/claude/c--Users-gotsb-OneDrive-Desktop-diplom/54ee3a97-b209-497c-b043-f8e18c9dfa86/scratchpad/'
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true })
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage()
const errors = []
page.on('pageerror', (e) => errors.push('PAGEERROR: ' + e.message))
page.on('dialog', (d) => d.accept())
await page.goto('http://localhost:5173', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(4200)
await page.click('button:has-text("Нэвтрэх")')
await page.waitForTimeout(400)
await page.fill('input[name="email"]', 'admin@medreh.mn')
await page.fill('input[name="pass"]', 'admin123')
await page.click('button[type="submit"]')
await page.waitForTimeout(1800)
await page.click('button:has-text("Хэрэглэгч · Дуу удирдах")')
await page.waitForTimeout(600)
await page.click('.auth-tabs button:has-text("Дууны сан")')
await page.waitForTimeout(400)
await page.screenshot({ path: SHOT + 'up1-form.png' })
// линкээр обложка өгч дуу нэмэх
await page.fill('input[name="title"]', 'Сарны гэрэл')
await page.fill('input[name="singer"]', 'Сарнай')
await page.fill('input[name="composer"]', 'Д.Дорж')
await page.fill('input[name="genre"]', 'Поп')
await page.setInputFiles('input[name="audio"]', 'public/tracks/song-2.mp3')
await page.fill('input[name="coverUrl"]', 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=70&fm=jpg')
await page.click('.adm-form button[type="submit"]')
await page.waitForTimeout(2500)
await page.screenshot({ path: SHOT + 'up2-added.png' })
await page.keyboard.press('Escape')
await page.waitForTimeout(1000)
// шинэ дуу дэлгэрэнгүй харах
await page.hover('.sp-card:has-text("Сарны гэрэл")')
await page.click('.sp-card:has-text("Сарны гэрэл") >> .sp-info')
await page.waitForTimeout(1200)
await page.screenshot({ path: SHOT + 'up3-detail.png' })
console.log('errors:', errors.length ? errors : 'none')
await browser.close()
